### PR TITLE
address 2 build problems on java1.8 on Red Hat 7

### PR DESCRIPTION
**Pull request by dckc**
for reference:

```
$ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.6 (Maipo)
```

### CODE REVIEW

**Comment by depryf** [comment]
@dckc I don't understand this request. Java 8 is basically out-of-life; I understand that many people are still using it and that longterm JDK's are still available and that's why the library remains compatible with Java 8. But that doesn't apply to its development, which was moved to Java 11 and now Java 12 a long time ago.

I see no reason at this point to revert the development itself to Java 8.

**Comment by dckc** [comment]
Ok.

Should the source compatibility line change?

https://github.com/imsweb/naaccr-xml/blob/master/build.gradle#L12

**Comment by depryf** [comment]
Well, the source compatibility can't really be moved to a higher version either because that would allow the source code to start using JDK API and/or language feature that wouldn't be compatible with the target level. While most IDE will help with that, I find it easier to just keep both levels together.

What would really be needed here is a third level indicating the expected version for Gradle to run under to build the project, and maybe there is a way to specify that but I never took the time to look into that (because it has never really caused any issues).

**Comment by dckc** [comment]
Some sort of documentation that "development ... moved to Java 11 and now Java 12" would be helpful. A comment in `build.gradle`? A note in a `CONTRIBUTING.md` file?

**Comment by depryf** [comment]
I don't get much contributions on the few libraries I maintain and so I wasn't familiar with the CONTRIBUTING file but it makes a lot of sense and I added one for this project.

**Pull request closed without merging**
